name: Build and run heimdall_tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-latest, macos-latest, windows-latest]
        ruby: [ 2.5, 2.6, 2.7, 3.0 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Test on Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build gem and run it
        run: |
          # Install gems required for building
          gem install bundler git-lite-version-bump
          gem build heimdall_tools.gemspec
          gem install heimdall_tools*.gem
          heimdall_tools help
          heimdall_tools version
