name: Build and run heimdall_tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [ '2.4', '2.5', '2.6', '2.7' ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Test on Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build gem and run it
        run: |
          gem build heimdall_tools.gemspec
          gem install heimdall_tools-*.gem
          heimdall_tools help
          heimdall_tools version
